### 1. Información de la API
curl http://localhost:3000/
### 2. Obtener todos los inmuebles
curl http://localhost:3000/inmuebles
### 3. Obtener un inmueble específico (se dedebe reemplazar `:ingresar_id` por un ID válido ya que se autogeneran para cada iteracion)
curl http://localhost:3000/inmuebles/:ingresar_id
### 4. Crear un nuevo inmueble 
curl -X POST http://localhost:3000/inmuebles \
  -H "Content-Type: application/json" \
  -d '{"direccion": "Calle super Falsa 123",
       "cant_ambientes": 5,
       "orientacion": "Este",
       "descripcion": "Una casa re fachera mal"}'
### 5. Actualizar un inmueble existente (se dedebe reemplazar `:ingresar_id` por un ID válido ya que se autogeneran para cada iteracion)
curl -X PUT http://localhost:3000/inmuebles/:ingresar_id \
  -H "Content-Type: application/json" \
  -d '{"direccion": "Calle Falsa 124",
       "cant_ambientes": 3,
       "orientacion": "Noreste",
       "descripcion": "Departamento luminoso con patio"}'
### 6. Eliminar un inmueble (se dedebe reemplazar `:ingresar_id` por un ID válido ya que se autogeneran para cada iteracion)
curl -X DELETE http://localhost:3000/inmuebles/:ingresar_id